version: "3"
services:
  api:
    container_name: release_notes_api
    build:
      context: ./api
      dockerfile: Dockerfile
    volumes:
      - "./api/src:/app/src"
    environment:
      NODE_ENV: ${NODE_ENV}
      VERSION: ${API_VERSION}
      HOST: ${API_HOST}
      PORT: ${API_PORT}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_URL: postgres://${DB_USERNAME}:${DB_PASSWORD}@postgres:${DB_PORT}/${DB_NAME}
    ports:
      - ${API_PORT}:${API_PORT}
    links:
      - postgres
    depends_on:
      - postgres

  web:
    container_name: release_notes_web
    build:
      context: ./web
      dockerfile: Dockerfile
    volumes:
      - "./web/src:/app/src"
    environment:
      NODE_ENV: ${NODE_ENV}
      API_VERSION: ${API_VERSION}
      API_HOST: ${API_HOST}
      API_PORT: ${API_PORT}
      HOST: ${WEB_HOST}
      PORT: ${WEB_PORT}
    ports:
      - ${WEB_PORT}:${WEB_PORT}
    links:
      - api
    depends_on:
      - api

  postgres:
    container_name: release_notes_db
    image: postgres:10.7-alpine
    environment:
      COMPOSE_HTTP_TIMEOUT: 200000
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
    - ${DB_PORT}:${DB_PORT}
