export const LOAD_APPLICATIONS_LIST = 'LOAD_APPLICATIONS_LIST';
export const LOAD_APPLICATIONS_SUCCESS = 'LOAD_APPLICATIONS_SUCCESS';
export const LOAD_APPLICATIONS_ERROR = 'LOAD_APPLICATIONS_ERROR';
export const CREATE_APPLICATION = 'CREATE_APPLICATION';
export const CREATE_APPLICATION_SUCCESS = 'CREATE_APPLICATION_SUCCESS';
export const CREATE_APPLICATION_ERROR = 'CREATE_APPLICATION_ERROR';
export const LOAD_APPLICATIONS_UPDATE_FILTERS = 'LOAD_APPLICATIONS_UPDATE_FILTERS';
