export const LOAD_NOTES_LIST = 'LOAD_NOTES_LIST';
export const LOAD_NOTES_LIST_SUCCESS = 'LOAD_NOTES_LIST_SUCCESS';
export const LOAD_NOTES_LIST_ERROR = 'LOAD_NOTES_LIST_ERROR';
export const LOAD_APPLICATION = 'LOAD_APPLICATION';
export const LOAD_APPLICATION_SUCCESS = 'LOAD_APPLICATION_SUCCESS';
export const LOAD_APPLICATION_ERROR = 'LOAD_APPLICATION_ERROR';
export const CLEAR_NOTES_LIST = 'CLEAR_NOTES_LIST';
