export const LOAD_NOTES_LIST = 'LOAD_NOTES_LIST';
export const LOAD_NOTES_LIST_SUCCESS = 'LOAD_NOTES_LIST_SUCCESS';
export const LOAD_NOTES_LIST_ERROR = 'LOAD_NOTES_LIST_ERROR';
export const CREATE_NOTE = 'CREATE_NOTE';
export const CREATE_NOTE_SUCCESS = 'CREATE_NOTE_SUCCESS';
export const CREATE_NOTE_ERROR = 'CREATE_NOTE_ERROR';
export const LOAD_NOTES_UPDATE_FILTERS = 'LOAD_NOTES_UPDATE_FILTERS';
