export const LOAD_APPLICATIONS_LIST = 'LOAD_APPLICATIONS_LIST';
export const LOAD_APPLICATIONS_SUCCESS = 'LOAD_APPLICATIONS_SUCCESS';
export const LOAD_APPLICATIONS_ERROR = 'LOAD_APPLICATIONS_ERROR';
